# Generated by Django 4.2.16 on 2024-11-29 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipecard_method'),
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(choices=[('grams', 'Grams'), ('kilograms', 'Kilograms'), ('cups', 'Cups'), ('tablespoon', 'Tablespoon'), ('teaspoon', 'Teaspoon'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.recipecard')),
            ],
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
