# Generated by Django 4.2.16 on 2024-11-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecard',
            name='category',
            field=models.CharField(choices=[('GF', 'Gluten Free'), ('QM', '20mins or less'), ('Vg', 'Vegan'), ('V', 'Vegetairine')], max_length=2),
        ),
        migrations.AlterField(
            model_name='recipecard',
            name='tag',
            field=models.SlugField(max_length=100),
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
