# Generated by Django 4.2.16 on 2024-11-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipecard_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecard',
            name='method',
            field=models.TextField(null=True),
        ),
    ]
